In [1]:
import numpy as np


# Softmax

In [4]:
a = np.random.randn(5)
expa = np.exp(a)
answer = expa / expa.sum()

In [5]:
answer

array([ 0.17181731,  0.16691466,  0.01239089,  0.28035338,  0.36852377])

In [8]:
A = np.random.randn(100, 5)
expA = np.exp(A)
answer = expA / expA.sum(axis = 1, keepdims=True)

In [11]:
answer.sum(axis=0)

array([ 19.50671126,  17.44768056,  20.08331911,  22.50389065,  20.45839842])

In [19]:
A[:,None]


array([[[-0.79743914, -1.45460735,  0.79139528, -0.18149945, -1.25231936]],

       [[ 0.21328936,  1.99164594, -0.7730228 ,  0.53759246, -0.21959042]],

       [[ 0.46077775,  0.96098056,  1.17059542, -1.42437888, -0.92096322]],

       [[ 0.30504629,  1.6953667 ,  0.59509384,  1.57388889,  0.7523209 ]],

       [[-0.131261  , -1.50681604, -0.89160143, -0.8560084 ,  0.69117833]],

       [[ 0.95630748,  1.10859154,  1.65759873,  1.05483387,  0.42421163]],

       [[ 0.42785309, -0.06539551, -0.36113577,  0.10973734,  1.47302047]],

       [[ 0.53228118, -0.44468237,  0.78498586,  1.25011261,  0.72463955]],

       [[ 0.63133801,  0.09213482,  0.49364178, -0.31609092, -0.50480568]],

       [[ 0.39398648, -0.49586758,  0.29340092,  1.89817165, -0.96484195]],

       [[ 0.06289483,  0.59944704, -0.12080017, -0.05089708,  0.44883209]],

       [[ 0.11531491,  1.04556989,  1.07999998, -1.89799454, -0.28328383]],

       [[-0.98286525, -0.1454357 ,  0.93837661, -1.03929881, -0.82085409]],


# forwardprop

In [14]:
import matplotlib.pyplot as plt

In [15]:
Nclass = 500

#gaussian clouds
X1 = np.random.randn(Nclass, 2) + np.array([0, -2])
X2 = np.random.randn(Nclass, 2) + np.array([2, 2])
X3 = np.random.randn(Nclass, 2) + np.array([-2, 2])
plt.scatter( X[:,0])